// frontend/src/App.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import type { Presentation, Slide, Theme } from '$lib/types';
	import {
		presentation,
		currentSlide,
		currentSlideIndex,
		currentFragmentIndex,
		loadPresentation,
		setupHashChangeListener,
		themeOverride
	} from '$lib/stores/presentation';
	import {
		connectWebSocket,
		disconnectWebSocket,
		detectStaticMode,
		getWebSocketClient
	} from '$lib/stores/websocket';
	import { setupKeyboardNavigation } from '$lib/utils/keyboard';
	import SlideContainer from '$lib/components/SlideContainer.svelte';
	import SlideRenderer from '$lib/components/SlideRenderer.svelte';
	import ProgressBar from '$lib/components/ProgressBar.svelte';
	import SlideOverview from '$lib/components/SlideOverview.svelte';
	import ConnectionIndicator from '$lib/components/ConnectionIndicator.svelte';

	// ============================================================================
	// State
	// ============================================================================

	let isLoading = $state(true);
	let loadError = $state<string | null>(null);
	let isOverviewOpen = $state(false);
	let direction = $state<'forward' | 'backward'>('forward');

	// Store values
	let presentationData = $state<Presentation | null>(null);
	let currentSlideData = $state<Slide | null>(null);
	let slideIndex = $state(0);
	let fragmentIndex = $state(-1);
	let slides = $state<Slide[]>([]);
	let currentThemeOverride = $state<string | null>(null);

	// Print mode detection (for PDF export - shows all fragments)
	const isPrintMode = typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('print') === 'true';

	// ============================================================================
	// Derived Values
	// ============================================================================

	// Theme override from WebSocket takes precedence over presentation config
	let theme = $derived((currentThemeOverride ?? presentationData?.config?.theme ?? 'paper') as Theme);
	let aspectRatio = $derived(presentationData?.config?.aspectRatio ?? '16:9');
	let showProgressBar = $derived(presentationData?.config?.showProgressBar !== false);
	let themeColors = $derived(presentationData?.config?.themeColors);
	let customTheme = $derived(presentationData?.config?.customTheme);
	let transitionDuration = $derived(presentationData?.config?.transitionDuration ?? 400);

	// Track custom theme link element
	let customThemeLinkEl: HTMLLinkElement | null = null;

	// ============================================================================
	// Store Subscriptions
	// ============================================================================

	let unsubscribers: (() => void)[] = [];

	// ============================================================================
	// Custom Theme Loading
	// ============================================================================

	/**
	 * Load custom theme CSS file via a dynamic link element.
	 * Removes any previously loaded custom theme first.
	 */
	function loadCustomTheme(hasCustomTheme: boolean): void {
		// Remove existing custom theme link if present
		if (customThemeLinkEl) {
			customThemeLinkEl.remove();
			customThemeLinkEl = null;
		}

		// If no custom theme, we're done
		if (!hasCustomTheme) {
			return;
		}

		// Create link element for custom theme CSS
		const link = document.createElement('link');
		link.rel = 'stylesheet';
		link.type = 'text/css';
		// Add cache-busting timestamp for dev mode reload
		link.href = `/api/custom-theme.css?t=${Date.now()}`;
		link.id = 'custom-theme-css';

		// Handle load errors gracefully
		link.onerror = () => {
			console.warn('[tap] Custom theme CSS failed to load. Using default theme.');
		};

		// Insert after other stylesheets to ensure custom theme overrides defaults
		document.head.appendChild(link);
		customThemeLinkEl = link;
	}

	// React to custom theme changes
	$effect(() => {
		loadCustomTheme(!!customTheme);
	});

	// ============================================================================
	// Fetch Presentation
	// ============================================================================

	async function fetchPresentation(): Promise<void> {
		try {
			// First check for embedded data (static build)
			const embeddedScript = document.getElementById('presentation-data');
			if (embeddedScript) {
				try {
					const data = JSON.parse(embeddedScript.textContent || '{}') as Presentation;
					if (data.slides && data.slides.length > 0) {
						loadPresentation(data);
						isLoading = false;
						return;
					}
				} catch {
					// Fall through to API fetch
				}
			}

			// Fetch from API
			const response = await fetch('/api/presentation');
			if (!response.ok) {
				throw new Error(`Failed to load presentation: ${response.statusText}`);
			}
			const data = (await response.json()) as Presentation;
			loadPresentation(data);
			isLoading = false;
		} catch (error) {
			loadError = error instanceof Error ? error.message : 'Failed to load presentation';
			isLoading = false;
		}
	}

	// ============================================================================
	// Overview Handlers
	// ============================================================================

	function toggleOverview(): void {
		isOverviewOpen = !isOverviewOpen;
	}

	function closeOverview(): void {
		isOverviewOpen = false;
	}

	function isOverviewOpenFn(): boolean {
		return isOverviewOpen;
	}

	// ============================================================================
	// WebSocket Broadcasting
	// ============================================================================

	// Track the last broadcasted slide index to avoid broadcasting on fragment changes
	let lastBroadcastedSlideIndex = -1;

	function broadcastSlide(): void {
		const client = getWebSocketClient();
		// Read the current slide index from the store
		let currentIndex = 0;
		const unsubscribe = currentSlideIndex.subscribe((value) => {
			currentIndex = value;
		});
		unsubscribe();

		// Only broadcast if the slide index actually changed (not just a fragment reveal)
		if (currentIndex !== lastBroadcastedSlideIndex) {
			lastBroadcastedSlideIndex = currentIndex;
			client.send({
				type: 'slide',
				slideIndex: currentIndex
			});
		}
	}

	// ============================================================================
	// Lifecycle
	// ============================================================================

	onMount(async () => {
		// Set up store subscriptions
		unsubscribers.push(
			presentation.subscribe((value) => {
				presentationData = value;
				slides = value?.slides ?? [];
			})
		);

		unsubscribers.push(
			currentSlide.subscribe((value) => {
				currentSlideData = value;
			})
		);

		unsubscribers.push(
			currentSlideIndex.subscribe((value) => {
				// Track direction for transitions
				if (value > slideIndex) {
					direction = 'forward';
				} else if (value < slideIndex) {
					direction = 'backward';
				}
				slideIndex = value;
			})
		);

		unsubscribers.push(
			currentFragmentIndex.subscribe((value) => {
				fragmentIndex = value;
			})
		);

		unsubscribers.push(
			themeOverride.subscribe((value) => {
				currentThemeOverride = value;
			})
		);

		// Set up hash change listener
		const hashCleanup = setupHashChangeListener();
		unsubscribers.push(hashCleanup);

		// Set up keyboard navigation
		const keyboardCleanup = setupKeyboardNavigation({
			onToggleOverview: toggleOverview,
			isOverviewOpen: isOverviewOpenFn,
			onNavigate: broadcastSlide
		});
		unsubscribers.push(keyboardCleanup);

		// Detect static mode
		await detectStaticMode();

		// Connect WebSocket (will handle reconnection automatically)
		connectWebSocket();

		// Fetch presentation data
		await fetchPresentation();
	});

	onDestroy(() => {
		// Clean up all subscriptions
		unsubscribers.forEach((unsub) => unsub());

		// Clean up custom theme link
		if (customThemeLinkEl) {
			customThemeLinkEl.remove();
			customThemeLinkEl = null;
		}

		// Disconnect WebSocket
		disconnectWebSocket();
	});
</script>

<svelte:head>
	<title>{presentationData?.config?.title ?? 'Tap Presentation'}</title>
</svelte:head>

<main class="app">
	{#if isLoading}
		<div class="loading-container">
			<div class="loading-spinner"></div>
			<p class="text-slide-body font-sans">Loading presentation...</p>
		</div>
	{:else if loadError}
		<div class="error-container">
			<h1>Error</h1>
			<p>{loadError}</p>
			<button onclick={() => window.location.reload()}>Reload</button>
		</div>
	{:else if presentationData && currentSlideData}
		<!-- Main slide view -->
		<SlideContainer {aspectRatio} {theme} {themeColors}>
			{#key slideIndex}
				<SlideRenderer
					slide={currentSlideData}
					visibleFragments={isPrintMode ? 999 : fragmentIndex}
					active={true}
					{direction}
					{transitionDuration}
					{theme}
				/>
			{/key}
		</SlideContainer>

		<!-- Progress bar -->
		<ProgressBar show={showProgressBar} />

		<!-- Connection indicator (hidden in print mode for PDF export) -->
		{#if !isPrintMode}
			<ConnectionIndicator />
		{/if}

		<!-- Slide overview modal -->
		<SlideOverview
			{slides}
			isOpen={isOverviewOpen}
			onClose={closeOverview}
		/>
	{:else}
		<div class="empty-container">
			<h1>No Presentation</h1>
			<p>No presentation data available.</p>
		</div>
	{/if}
</main>

<style>
	.app {
		width: 100vw;
		height: 100vh;
		overflow: hidden;
		background-color: #000;
	}

	/* Loading state */
	.loading-container {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		height: 100vh;
		gap: 1rem;
		color: #fff;
		font-family: system-ui, -apple-system, sans-serif;
	}

	.loading-spinner {
		width: 40px;
		height: 40px;
		border: 3px solid rgba(255, 255, 255, 0.2);
		border-top-color: #7c3aed;
		border-radius: 50%;
		animation: spin 1s linear infinite;
	}

	@keyframes spin {
		to {
			transform: rotate(360deg);
		}
	}

	/* Error state */
	.error-container {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		height: 100vh;
		gap: 1rem;
		color: #fff;
		font-family: system-ui, -apple-system, sans-serif;
		text-align: center;
		padding: 2rem;
	}

	.error-container h1 {
		margin: 0;
		font-size: 2rem;
		color: #ef4444;
	}

	.error-container p {
		margin: 0;
		color: rgba(255, 255, 255, 0.7);
		max-width: 400px;
	}

	.error-container button {
		margin-top: 1rem;
		padding: 0.75rem 1.5rem;
		background-color: #7c3aed;
		color: #fff;
		border: none;
		border-radius: 6px;
		font-size: 1rem;
		cursor: pointer;
		transition: background-color 0.2s ease;
	}

	.error-container button:hover {
		background-color: #6d28d9;
	}

	.error-container button:focus {
		outline: 2px solid #7c3aed;
		outline-offset: 2px;
	}

	/* Empty state */
	.empty-container {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		height: 100vh;
		gap: 1rem;
		color: #fff;
		font-family: system-ui, -apple-system, sans-serif;
		text-align: center;
	}

	.empty-container h1 {
		margin: 0;
		font-size: 2rem;
	}

	.empty-container p {
		margin: 0;
		color: rgba(255, 255, 255, 0.7);
	}
</style>

// frontend/src/App.tsx
/**
 * Root component for the main slide viewer.
 * Loads the presentation, wires up keyboard navigation and hot reload, and
 * renders the current slide inside the scaled canvas, along with the
 * progress bar, the connection indicator, and the slide overview.
 */

import { useEffect, useRef, useState, type ReactNode } from 'react';
import {
	usePresentationStore,
	selectCurrentSlide,
	selectTotalSlides,
	loadPresentation,
	setupHashChangeListener
} from '$lib/stores/presentation';
import { useResolvedTheme } from '$lib/hooks/useResolvedTheme';
import {
	broadcastPresentationState,
	connectWebSocket,
	detectStaticMode,
	disconnectWebSocket
} from '$lib/stores/websocket';
import { setupKeyboardNavigation } from '$lib/utils/keyboard';
import { fetchPresentation } from '$lib/utils/fetchPresentation';
import { SlideCanvas } from '$lib/components/SlideCanvas';
import { Slide } from '$lib/components/Slide';
import { SlideTransition } from '$lib/components/SlideTransition';
import { ProgressBar } from '$lib/components/ProgressBar';
import { ConnectionIndicator } from '$lib/components/ConnectionIndicator';
import { SlideOverview } from '$lib/components/SlideOverview';
import { ShortcutHelp } from '$lib/components/ShortcutHelp';
import { AUDIENCE_SHORTCUTS } from '$lib/utils/shortcuts';
import { resolveTransition, type TransitionDirection } from '$lib/utils/transitions';

const PRINT_MODE =
	typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('print') === 'true';

// A stepped or fragment screenshot (tap screenshot --step/--fragment) opens
// this live, non-print viewer so it can render an exact presenter state -
// print mode always shows the final step and fragment, which a stepped
// capture must not. It still runs against a temporary server that never
// serves the websocket route (see internal/cli/screenshot.go), so it must
// behave like print mode for the websocket: never connect, and never show
// the connection badge, or a capture bakes "Reconnecting..." into the PNG.
const CAPTURE_MODE =
	typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('capture') === 'true';

// `tap screenshot --wait <ms>` (see internal/pdf/capture.go) keeps a capture
// genuinely live - a running animation is exactly what --wait is for - so it
// skips the settled treatment below. Without --wait, the default, a capture
// is a still: `?live=true` is absent and the capture settles.
const CAPTURE_LIVE =
	typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('live') === 'true';

// Whether a deck component (and CSS-driven theme animations, via
// SlideCanvas's data-print attribute) should render its settled state
// instead of animating: true print (?print=true, which also forces the
// final step/fragment - see the step/fragmentIndex props below) and a
// non-live capture both want this; a live capture (--wait) does not, since
// the whole point of --wait is to catch a running animation partway
// through. Unlike print mode, a settled capture keeps the REQUESTED step
// and fragment - see SETTLE's callers below, and Slide.tsx's
// deckComponentPrintMode, which is this same OR applied at the slide level
// for the same reason.
const SETTLE = PRINT_MODE || (CAPTURE_MODE && !CAPTURE_LIVE);

/**
 * Tracks the direction of the most recent slide change by comparing the
 * current index to the previous render's. Read during render, updated in
 * the same render pass, so it is always current for the transition below.
 */
function useSlideDirection(currentIndex: number): TransitionDirection {
	const previousIndexRef = useRef(currentIndex);
	const directionRef = useRef<TransitionDirection>('forward');

	if (previousIndexRef.current !== currentIndex) {
		directionRef.current = currentIndex >= previousIndexRef.current ? 'forward' : 'backward';
		previousIndexRef.current = currentIndex;
	}

	return directionRef.current;
}

export default function App() {
	const [isLoading, setIsLoading] = useState(true);
	const [loadError, setLoadError] = useState<string | null>(null);
	const [overviewOpen, setOverviewOpen] = useState(false);
	const overviewOpenRef = useRef(overviewOpen);
	overviewOpenRef.current = overviewOpen;
	const [helpOpen, setHelpOpen] = useState(false);
	const helpOpenRef = useRef(helpOpen);
	helpOpenRef.current = helpOpen;

	const presentation = usePresentationStore((state) => state.presentation);
	const currentSlide = usePresentationStore(selectCurrentSlide);
	const currentSlideIndex = usePresentationStore((state) => state.currentSlideIndex);
	const totalSlides = usePresentationStore(selectTotalSlides);
	const currentFragmentIndex = usePresentationStore((state) => state.currentFragmentIndex);
	const currentStep = usePresentationStore((state) => state.currentStep);
	const scrollRevealed = usePresentationStore((state) => state.scrollRevealed);
	const scrollTriggerCount = usePresentationStore((state) => state.scrollTriggerCount);
	const direction = useSlideDirection(currentSlideIndex);

	const resolvedTheme = useResolvedTheme();
	const theme = resolvedTheme?.slug ?? 'base';
	const aspectRatio = presentation?.config?.aspectRatio ?? '16:9';
	const themeColors = presentation?.config?.themeColors;
	const customTheme = presentation?.config?.customTheme;
	const showProgressBar = presentation?.config?.showProgressBar !== false;
	const transition = resolveTransition(currentSlide?.transition, presentation?.config?.transition);

	useEffect(() => {
		let cancelled = false;

		async function load(): Promise<void> {
			try {
				const data = await fetchPresentation();
				if (cancelled) return;
				loadPresentation(data);
				setIsLoading(false);
			} catch (error) {
				if (cancelled) return;
				setLoadError(error instanceof Error ? error.message : 'Failed to load presentation');
				setIsLoading(false);
			}
		}

		void load();

		const hashCleanup = setupHashChangeListener();
		const keyboardCleanup = setupKeyboardNavigation({
			onNavigate: broadcastPresentationState,
			onToggleOverview: () => setOverviewOpen((open) => !open),
			isOverviewOpen: () => overviewOpenRef.current,
			onToggleHelp: () => setHelpOpen((open) => !open),
			isHelpOpen: () => helpOpenRef.current
		});

		// A print pass (PDF export, ?print=true) is a static snapshot of one
		// slide: it never connects the websocket, so it can never have the
		// hub's live state applied out from under the screenshot. A static
		// build has no server either, so the websocket must never be opened
		// (and never retried) once static mode is confirmed. A stepped or
		// fragment capture (?capture=true) is not a static snapshot, but it
		// must never connect either - see CAPTURE_MODE above.
		if (!PRINT_MODE && !CAPTURE_MODE) {
			void detectStaticMode().then((isStatic) => {
				if (!cancelled && !isStatic) {
					connectWebSocket();
				}
			});
		}

		return () => {
			cancelled = true;
			hashCleanup();
			keyboardCleanup();
			disconnectWebSocket();
		};
	}, []);

	useEffect(() => {
		document.title = presentation?.config?.title ?? 'Tap Presentation';
	}, [presentation?.config?.title]);

	useEffect(() => {
		if (!customTheme) {
			return;
		}

		const link = document.createElement('link');
		link.rel = 'stylesheet';
		link.type = 'text/css';
		link.href = `/api/custom-theme.css?t=${Date.now()}`;
		link.id = 'custom-theme-css';
		link.onerror = () => {
			console.warn('[tap] Custom theme CSS failed to load. Using default theme.');
		};
		document.head.appendChild(link);

		return () => {
			link.remove();
		};
	}, [customTheme]);

	let content: ReactNode;

	if (isLoading) {
		content = (
			<div className="loading-container">
				<div className="loading-spinner" />
				<p>Loading presentation...</p>
			</div>
		);
	} else if (loadError) {
		content = (
			<div className="error-container">
				<h1>Error</h1>
				<p>{loadError}</p>
				<button onClick={() => window.location.reload()}>Reload</button>
			</div>
		);
	} else if (!presentation || !currentSlide) {
		content = (
			<div className="empty-container">
				<h1>No Presentation</h1>
				<p>No presentation data available.</p>
			</div>
		);
	} else {
		content = (
			<>
				<SlideCanvas
					aspectRatio={aspectRatio}
					theme={theme}
					themeColors={themeColors}
					printMode={SETTLE}
				>
					<SlideTransition
						slideKey={currentSlideIndex}
						transition={transition}
						direction={direction}
						printMode={SETTLE}
					>
						<Slide
							slide={currentSlide}
							active
							printMode={PRINT_MODE}
							settleComponents={SETTLE}
							fragmentIndex={PRINT_MODE ? currentSlide.fragmentCount : currentFragmentIndex}
							step={PRINT_MODE ? currentSlide.steps : currentStep}
							total={totalSlides}
							scrollRevealed={scrollRevealed}
							scrollTriggerCount={scrollTriggerCount}
							mermaidOverrides={resolvedTheme?.mermaid}
						/>
					</SlideTransition>
				</SlideCanvas>

				<ProgressBar show={showProgressBar} />

				{!PRINT_MODE && !CAPTURE_MODE ? <ConnectionIndicator /> : null}

				<SlideOverview
					slides={presentation.slides}
					theme={theme}
					aspectRatio={aspectRatio}
					isOpen={overviewOpen}
					onClose={() => setOverviewOpen(false)}
				/>

				<ShortcutHelp groups={AUDIENCE_SHORTCUTS} theme={theme} isOpen={helpOpen} onClose={() => setHelpOpen(false)} />
			</>
		);
	}

	return <div className="slide-renderer">{content}</div>;
}
