// frontend/src/lib/components/ConnectionIndicator.tsx
/**
 * Subtle corner indicator shown while the WebSocket connection is down.
 * Hidden entirely once connected, in static mode, or before static mode
 * detection finishes, so it never flashes on initial load.
 */

import { useConnectionStore } from '$lib/stores/websocket';

export function ConnectionIndicator() {
	const connected = useConnectionStore((state) => state.connected);
	const reconnecting = useConnectionStore((state) => state.reconnecting);
	const reconnectAttempt = useConnectionStore((state) => state.reconnectAttempt);
	const staticMode = useConnectionStore((state) => state.staticMode);
	const staticModeDetected = useConnectionStore((state) => state.staticModeDetected);

	const shouldShow = staticModeDetected && !staticMode && !connected;
	if (!shouldShow) {
		return null;
	}

	const statusText = reconnecting && reconnectAttempt > 0 ? `Reconnecting... (${reconnectAttempt})` : 'Disconnected';

	return (
		<div
			className={`connection-indicator disconnected${reconnecting ? ' reconnecting' : ''}`}
			role="status"
			aria-live="polite"
			aria-label={statusText}
		>
			<span className={`indicator-dot${reconnecting ? ' pulse' : ''}`} />
			<span className="indicator-text">{statusText}</span>
		</div>
	);
}

// frontend/src/lib/components/ConnectionIndicator.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import {
		connected,
		reconnecting,
		reconnectAttempt,
		staticMode,
		staticModeDetected
	} from '$lib/stores/websocket';

	// ============================================================================
	// State
	// ============================================================================

	let isConnected = $state(false);
	let isReconnecting = $state(false);
	let attemptNumber = $state(0);
	let isStaticMode = $state(false);
	let staticDetectionComplete = $state(false);

	// ============================================================================
	// Store Subscriptions
	// ============================================================================

	let unsubscribers: (() => void)[] = [];

	onMount(() => {
		unsubscribers.push(
			connected.subscribe((value) => {
				isConnected = value;
			})
		);

		unsubscribers.push(
			reconnecting.subscribe((value) => {
				isReconnecting = value;
			})
		);

		unsubscribers.push(
			reconnectAttempt.subscribe((value) => {
				attemptNumber = value;
			})
		);

		unsubscribers.push(
			staticMode.subscribe((value) => {
				isStaticMode = value;
			})
		);

		unsubscribers.push(
			staticModeDetected.subscribe((value) => {
				staticDetectionComplete = value;
			})
		);
	});

	onDestroy(() => {
		unsubscribers.forEach((unsub) => unsub());
	});

	// ============================================================================
	// Computed Values
	// ============================================================================

	/**
	 * Whether to show the indicator.
	 * Don't show in static mode or when connected.
	 * Only show after static mode detection is complete to avoid flashing.
	 */
	let shouldShow = $derived(
		staticDetectionComplete && !isStaticMode && !isConnected
	);

	/**
	 * Status text to display.
	 */
	let statusText = $derived(() => {
		if (isReconnecting && attemptNumber > 0) {
			return `Reconnecting... (${attemptNumber})`;
		}
		return 'Disconnected';
	});
</script>

{#if shouldShow}
	<div
		class="connection-indicator"
		class:reconnecting={isReconnecting}
		role="status"
		aria-live="polite"
		aria-label={statusText()}
	>
		<span class="indicator-dot" class:pulse={isReconnecting}></span>
		<span class="indicator-text">{statusText()}</span>
	</div>
{/if}

<style>
	/* Animation keyframes kept in component - these are component-specific */
	.connection-indicator {
		animation: slideIn 0.3s ease-out;
	}

	@keyframes slideIn {
		from {
			opacity: 0;
			transform: translateY(-10px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}

	.indicator-dot.pulse {
		animation: pulse 1.5s ease-in-out infinite;
	}

	@keyframes pulse {
		0%,
		100% {
			opacity: 1;
			transform: scale(1);
		}
		50% {
			opacity: 0.5;
			transform: scale(0.8);
		}
	}

	/* Reduced motion support */
	@media (prefers-reduced-motion: reduce) {
		.connection-indicator {
			animation: none;
		}

		.indicator-dot.pulse {
			animation: none;
		}
	}
</style>
