// frontend/src/lib/components/MapSlide.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import maplibregl from 'maplibre-gl';
	import type { MapConfig } from '$lib/types';
	import { resolveMapStyle, getMapLibreEasing } from '$lib/utils/map';

	// ============================================================================
	// Props
	// ============================================================================

	interface Props {
		/** Map configuration from parsed code block */
		config: MapConfig;
		/** Whether this slide is currently active */
		active?: boolean;
		/** Whether animation has been triggered */
		animationTriggered?: boolean;
		/** Whether in print/PDF mode (jump to end immediately) */
		isPrintMode?: boolean;
	}

	let {
		config,
		active = true,
		animationTriggered = false,
		isPrintMode = false
	}: Props = $props();

	// ============================================================================
	// State
	// ============================================================================

	let mapContainer: HTMLDivElement | undefined = $state();
	let map: maplibregl.Map | undefined = $state();
	let startMarker: maplibregl.Marker | undefined;
	let endMarker: maplibregl.Marker | undefined;
	let isMapReady = $state(false);
	let hasAnimated = $state(false);

	// ============================================================================
	// Computed
	// ============================================================================

	/**
	 * Check if reduced motion is preferred.
	 */
	function prefersReducedMotion(): boolean {
		if (typeof window === 'undefined') return false;
		return window.matchMedia('(prefers-reduced-motion: reduce)').matches;
	}

	/**
	 * Convert [lat, lng] to MapLibre's [lng, lat] format.
	 */
	function toMapLibreCoords(coords: [number, number]): [number, number] {
		return [coords[1], coords[0]];
	}

	// ============================================================================
	// Map Initialization
	// ============================================================================

	/**
	 * Initialize the map when the component mounts.
	 */
	function initializeMap(): void {
		if (!mapContainer || map) return;

		const styleUrl = resolveMapStyle(config.style);

		// Determine initial position based on mode
		const shouldShowEnd = isPrintMode || prefersReducedMotion();
		const initialCoords = shouldShowEnd ? config.end : config.start;
		const initialZoom = shouldShowEnd ? config.endZoom : config.zoom;

		map = new maplibregl.Map({
			container: mapContainer,
			style: styleUrl,
			center: toMapLibreCoords(initialCoords),
			zoom: initialZoom,
			pitch: config.pitch,
			bearing: config.bearing,
			attributionControl: { compact: true },
			interactive: false // Disable user interaction for presentation
		});

		// Set up load handler
		map.on('load', () => {
			if (!map) return;

			isMapReady = true;

			// Add path line if enabled
			if (config.showPath) {
				addPathLine();
			}

			// Add markers if enabled
			if (config.markers) {
				addMarkers();
			}

			// In print mode, ensure we're at end position and mark ready
			if (isPrintMode || prefersReducedMotion()) {
				jumpToEnd();
				hasAnimated = true;
			}

			// Expose map on window for E2E testing and PDF export
			if (typeof window !== 'undefined') {
				(window as unknown as { __tapMap: maplibregl.Map }).__tapMap = map;
				(window as unknown as { __tapMapReady: boolean }).__tapMapReady = true;
			}
		});

		map.on('error', (e) => {
			console.error('Map error:', e);
		});
	}

	/**
	 * Add start and end markers to the map.
	 */
	function addMarkers(): void {
		if (!map) return;

		// Create start marker (green)
		const startEl = document.createElement('div');
		startEl.className = 'map-marker map-marker-start';
		startEl.innerHTML = `
			<svg width="24" height="36" viewBox="0 0 24 36" fill="none" xmlns="http://www.w3.org/2000/svg">
				<path d="M12 0C5.373 0 0 5.373 0 12c0 9 12 24 12 24s12-15 12-24c0-6.627-5.373-12-12-12z" fill="#22c55e"/>
				<circle cx="12" cy="12" r="6" fill="white"/>
			</svg>
		`;

		startMarker = new maplibregl.Marker({ element: startEl })
			.setLngLat(toMapLibreCoords(config.start))
			.addTo(map);

		// Create end marker (red)
		const endEl = document.createElement('div');
		endEl.className = 'map-marker map-marker-end';
		endEl.innerHTML = `
			<svg width="24" height="36" viewBox="0 0 24 36" fill="none" xmlns="http://www.w3.org/2000/svg">
				<path d="M12 0C5.373 0 0 5.373 0 12c0 9 12 24 12 24s12-15 12-24c0-6.627-5.373-12-12-12z" fill="#ef4444"/>
				<circle cx="12" cy="12" r="6" fill="white"/>
			</svg>
		`;

		endMarker = new maplibregl.Marker({ element: endEl })
			.setLngLat(toMapLibreCoords(config.end))
			.addTo(map);
	}

	/**
	 * Add a path line connecting start and end points.
	 */
	function addPathLine(): void {
		if (!map) return;

		const geojson: GeoJSON.Feature<GeoJSON.LineString> = {
			type: 'Feature',
			properties: {},
			geometry: {
				type: 'LineString',
				coordinates: [toMapLibreCoords(config.start), toMapLibreCoords(config.end)]
			}
		};

		map.addSource('path-line', {
			type: 'geojson',
			data: geojson
		});

		map.addLayer({
			id: 'path-line',
			type: 'line',
			source: 'path-line',
			layout: {
				'line-join': 'round',
				'line-cap': 'round'
			},
			paint: {
				'line-color': '#3b82f6',
				'line-width': 3,
				'line-dasharray': [2, 2],
				'line-opacity': 0.8
			}
		});
	}

	// ============================================================================
	// Animation
	// ============================================================================

	/**
	 * Trigger the fly animation to the end position.
	 */
	export function triggerAnimation(): void {
		if (!map || !isMapReady || hasAnimated) return;

		// Check for reduced motion
		if (prefersReducedMotion()) {
			jumpToEnd();
			hasAnimated = true;
			return;
		}

		const easingFn = getMapLibreEasing(config.easing);

		map.flyTo({
			center: toMapLibreCoords(config.end),
			zoom: config.endZoom,
			pitch: config.pitch,
			bearing: config.bearing,
			duration: config.duration,
			easing: easingFn
		});

		hasAnimated = true;
	}

	/**
	 * Jump directly to the end position (no animation).
	 */
	function jumpToEnd(): void {
		if (!map) return;

		map.jumpTo({
			center: toMapLibreCoords(config.end),
			zoom: config.endZoom,
			pitch: config.pitch,
			bearing: config.bearing
		});
	}

	/**
	 * Reset the map to the start position.
	 */
	export function resetToStart(): void {
		if (!map || !isMapReady) return;

		// Use a quick animation or jump based on preference
		if (prefersReducedMotion()) {
			map.jumpTo({
				center: toMapLibreCoords(config.start),
				zoom: config.zoom,
				pitch: config.pitch,
				bearing: config.bearing
			});
		} else {
			map.flyTo({
				center: toMapLibreCoords(config.start),
				zoom: config.zoom,
				pitch: config.pitch,
				bearing: config.bearing,
				duration: 500 // Quick reset animation
			});
		}

		hasAnimated = false;
	}

	/**
	 * Check if the map has been animated.
	 */
	export function hasBeenAnimated(): boolean {
		return hasAnimated;
	}

	// ============================================================================
	// Lifecycle
	// ============================================================================

	onMount(() => {
		// Small delay to ensure container is properly sized
		requestAnimationFrame(() => {
			initializeMap();
		});
	});

	onDestroy(() => {
		// Clean up map instance to avoid WebGL context limits
		if (startMarker) {
			startMarker.remove();
			startMarker = undefined;
		}
		if (endMarker) {
			endMarker.remove();
			endMarker = undefined;
		}
		if (map) {
			map.remove();
			map = undefined;
		}

		// Clean up window references
		if (typeof window !== 'undefined') {
			delete (window as unknown as { __tapMap?: maplibregl.Map }).__tapMap;
			delete (window as unknown as { __tapMapReady?: boolean }).__tapMapReady;
		}
	});

	// Watch for animation trigger
	$effect(() => {
		if (animationTriggered && isMapReady && !hasAnimated) {
			triggerAnimation();
		}
	});

	// Watch for active state changes (reset when slide becomes active again)
	$effect(() => {
		if (active && map && isMapReady) {
			// Resize map in case container dimensions changed
			map.resize();
		}
	});
</script>

<div class="map-slide" bind:this={mapContainer}></div>

<style>
	.map-slide {
		width: 100%;
		height: 100%;
		position: absolute;
		top: 0;
		left: 0;
	}

	/* Import MapLibre CSS */
	:global(.maplibregl-map) {
		font-family: inherit;
	}

	/* Marker styles */
	:global(.map-marker) {
		cursor: default;
	}

	:global(.map-marker svg) {
		display: block;
	}

	/* Attribution styling to match presentation themes */
	:global(.maplibregl-ctrl-attrib) {
		font-size: 10px;
		background: rgba(255, 255, 255, 0.7);
		padding: 2px 5px;
		border-radius: 3px;
	}

	/* Hide attribution in fullscreen/print mode */
	@media print {
		:global(.maplibregl-ctrl-attrib) {
			display: none;
		}
	}
</style>

// frontend/src/lib/components/MapSlide.tsx
/**
 * Renders an animated MapLibre map for a `map` code block, driven entirely
 * by the presenter step passed from Slide: step 0 shows the start view,
 * step 1 flies to the end view, and print mode jumps straight to the end
 * view with no animation. This component has no store access; all state it
 * needs comes in as props.
 */

import { useEffect, useRef } from 'react';
import maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import type { MapConfig } from '$lib/types';
import { getMapLibreEasing, resolveMapStyle } from '../utils/map';

export interface MapSlideProps {
	/** Parsed configuration for the `map` code block. */
	config: MapConfig;
	/** Presenter step: 0 shows the start view, 1 shows or animates to the end view. */
	step: number;
	/** Whether this slide is currently shown to the viewer. */
	active?: boolean;
	/** Whether rendering for PDF export: jumps to the end view with no animation. */
	printMode?: boolean;
}

/** Duration in milliseconds for the quick reset animation back to the start view. */
const RESET_DURATION = 500;

function prefersReducedMotion(): boolean {
	if (typeof window === 'undefined') return false;
	return window.matchMedia('(prefers-reduced-motion: reduce)').matches;
}

/** Convert [lat, lng] to MapLibre's [lng, lat] format. */
function toMapLibreCoords(coords: [number, number]): [number, number] {
	return [coords[1], coords[0]];
}

function createMarkerElement(className: string, color: string): HTMLDivElement {
	const element = document.createElement('div');
	element.className = className;
	element.innerHTML = `
		<svg width="24" height="36" viewBox="0 0 24 36" fill="none" xmlns="http://www.w3.org/2000/svg">
			<path d="M12 0C5.373 0 0 5.373 0 12c0 9 12 24 12 24s12-15 12-24c0-6.627-5.373-12-12-12z" fill="${color}"/>
			<circle cx="12" cy="12" r="6" fill="white"/>
		</svg>
	`;
	return element;
}

export function MapSlide({ config, step, active = true, printMode = false }: MapSlideProps) {
	const containerRef = useRef<HTMLDivElement>(null);
	const mapRef = useRef<maplibregl.Map | null>(null);
	const startMarkerRef = useRef<maplibregl.Marker | null>(null);
	const endMarkerRef = useRef<maplibregl.Marker | null>(null);
	const isReadyRef = useRef(false);
	const previousStepRef = useRef(step);

	// Create the map once per config, positioned directly at the view that
	// matches the step it mounts at, so returning to an already-animated map
	// slide shows the end view without replaying the animation.
	useEffect(() => {
		const container = containerRef.current;
		if (!container) return;

		const showEnd = printMode || step >= 1;
		const initialCoords = showEnd ? config.end : config.start;
		const initialZoom = showEnd ? config.endZoom : config.zoom;

		const map = new maplibregl.Map({
			container,
			style: resolveMapStyle(config.style),
			center: toMapLibreCoords(initialCoords),
			zoom: initialZoom,
			pitch: config.pitch,
			bearing: config.bearing,
			attributionControl: { compact: true },
			interactive: false
		});
		mapRef.current = map;
		isReadyRef.current = false;

		map.on('load', () => {
			isReadyRef.current = true;

			if (config.showPath) {
				const geojson = {
					type: 'Feature' as const,
					properties: {},
					geometry: {
						type: 'LineString' as const,
						coordinates: [toMapLibreCoords(config.start), toMapLibreCoords(config.end)]
					}
				};
				map.addSource('path-line', { type: 'geojson', data: geojson });
				map.addLayer({
					id: 'path-line',
					type: 'line',
					source: 'path-line',
					layout: { 'line-join': 'round', 'line-cap': 'round' },
					paint: {
						'line-color': '#3b82f6',
						'line-width': 3,
						'line-dasharray': [2, 2],
						'line-opacity': 0.8
					}
				});
			}

			if (config.markers) {
				startMarkerRef.current = new maplibregl.Marker({
					element: createMarkerElement('map-marker map-marker-start', '#22c55e')
				})
					.setLngLat(toMapLibreCoords(config.start))
					.addTo(map);
				endMarkerRef.current = new maplibregl.Marker({
					element: createMarkerElement('map-marker map-marker-end', '#ef4444')
				})
					.setLngLat(toMapLibreCoords(config.end))
					.addTo(map);
			}

			// Expose the map instance for E2E testing and PDF export.
			if (typeof window !== 'undefined') {
				(window as unknown as { __tapMap: maplibregl.Map }).__tapMap = map;
				(window as unknown as { __tapMapReady: boolean }).__tapMapReady = true;
			}
		});

		map.on('error', (event) => {
			console.error('Map error:', event);
		});

		return () => {
			startMarkerRef.current?.remove();
			startMarkerRef.current = null;
			endMarkerRef.current?.remove();
			endMarkerRef.current = null;
			map.remove();
			mapRef.current = null;
			isReadyRef.current = false;

			if (typeof window !== 'undefined') {
				delete (window as unknown as { __tapMap?: maplibregl.Map }).__tapMap;
				delete (window as unknown as { __tapMapReady?: boolean }).__tapMapReady;
			}
		};
		// A new config identifies a distinct map slide, which gets a fresh map.
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [config]);

	// Animate between the start and end views when the step actually changes.
	// Skipped on mount (previousStepRef starts equal to step), which is what
	// lets a slide mounted at step 1 show the end view without replaying.
	useEffect(() => {
		const map = mapRef.current;
		const wasStep = previousStepRef.current;
		previousStepRef.current = step;

		if (!map || !isReadyRef.current || wasStep === step) {
			return;
		}

		if (step >= 1 && wasStep < 1) {
			if (printMode || prefersReducedMotion()) {
				map.jumpTo({
					center: toMapLibreCoords(config.end),
					zoom: config.endZoom,
					pitch: config.pitch,
					bearing: config.bearing
				});
			} else {
				map.flyTo({
					center: toMapLibreCoords(config.end),
					zoom: config.endZoom,
					pitch: config.pitch,
					bearing: config.bearing,
					duration: config.duration,
					easing: getMapLibreEasing(config.easing)
				});
			}
		} else if (step < 1 && wasStep >= 1) {
			if (prefersReducedMotion()) {
				map.jumpTo({
					center: toMapLibreCoords(config.start),
					zoom: config.zoom,
					pitch: config.pitch,
					bearing: config.bearing
				});
			} else {
				map.flyTo({
					center: toMapLibreCoords(config.start),
					zoom: config.zoom,
					pitch: config.pitch,
					bearing: config.bearing,
					duration: RESET_DURATION
				});
			}
		}
	}, [step, printMode, config]);

	// Resize the map when the slide becomes the active one again, in case its
	// container dimensions changed while it was hidden.
	useEffect(() => {
		const map = mapRef.current;
		if (active && map && isReadyRef.current) {
			map.resize();
		}
	}, [active]);

	return <div className="map-slide" ref={containerRef} />;
}
