// frontend/src/lib/layouts/LayoutTitle.svelte
<script lang="ts">
	/**
	 * LayoutTitle - Centered title slide with optional subtitle.
	 *
	 * This layout is used for:
	 * - Title slides at the beginning of presentations
	 * - Section dividers with prominent headings
	 * - Any slide where you want a centered, bold title
	 *
	 * Expected HTML structure:
	 * - h1: Main title (required)
	 * - p: Subtitle (optional)
	 */

	import type { Snippet } from 'svelte';

	// ============================================================================
	// Props
	// ============================================================================

	interface Props {
		/** Slot content containing the slide HTML */
		children: Snippet;
	}

	let { children }: Props = $props();
</script>

<div class="layout-title">
	<div class="title-content">
		{@render children()}
	</div>
</div>

<style>
	/* Legacy CSS removed - will be replaced with Tailwind in US-107A */
</style>

// frontend/src/lib/layouts/LayoutTitle.tsx
/**
 * LayoutTitle - centered title slide with an optional subtitle.
 * Used for the opening slide of a presentation or a section title.
 */

import type { LayoutProps } from '$lib/types';
import { Slot } from '../components/Slot';

export function LayoutTitle({ slots }: LayoutProps) {
	return (
		<div className="layout-title">
			<Slot html={slots.default} className="slot-default" />
		</div>
	);
}
