// frontend/src/lib/layouts/LayoutCodeFocus.svelte
<script lang="ts">
	/**
	 * LayoutCodeFocus - Full-width code block layout.
	 *
	 * This layout is used for:
	 * - Slides that focus on a single code snippet
	 * - Live code demonstrations
	 * - Code walkthroughs with optional title/description
	 *
	 * Expected HTML structure:
	 * - h2 or h3: Optional title above the code (optional)
	 * - pre/code: The main code block (required)
	 * - p: Optional description or explanation (optional)
	 *
	 * The code block takes prominence, filling most of the available space.
	 */

	import type { Snippet } from 'svelte';

	// ============================================================================
	// Props
	// ============================================================================

	interface Props {
		/** Slot content containing the slide HTML */
		children: Snippet;
	}

	let { children }: Props = $props();
</script>

<!--
	LayoutCodeFocus uses CSS from layouts.css for code-centric presentation.
	The code block takes prominence, filling most of the available space.
-->
<div class="layout-code-focus">
	{@render children()}
</div>

// frontend/src/lib/layouts/LayoutCodeFocus.tsx
/**
 * LayoutCodeFocus - full-width code block layout.
 * The code block takes prominence, filling most of the available space.
 */

import type { LayoutProps } from '$lib/types';
import { Slot } from '../components/Slot';

export function LayoutCodeFocus({ slots }: LayoutProps) {
	return (
		<div className="layout-code-focus">
			<Slot html={slots.default} className="slot-default" />
		</div>
	);
}
